name: Publish Infrastructure Images to GHCR

# Trigger this pipeline every time you push code to the 'main' branch
on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  # GitHub automatically injects your user/repo name here
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-mosquitto:
    runs-on: ubuntu-latest

    # We must explicitely grant permission to write to the registry
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          # GitHub provides a secure temporary token automatically
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: {{ env.REGISTRY }} / ${{ env.IMAGE_NAME }}-broker
          tags: type=sha # This tags the image with the specific commit ID

      - name: Buildand push Docker image
        uses: docker/build-push-action@v5
        with:
          # Context tells Docker where to look for the Dockerfile
          context: ./infra/mosquitto
          push : true
          tags: ${{ steps.meta.outputs.tags }}, ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-broker:latest
          labels: ${{ steps.meta.outputs.labels }}
