name: CI/CD Infrastructure and Apps

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'infra/build-env/**'

env:
  REGISTRY: ghcr.io
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-rust:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/rust-builder:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rust Cache
        uses: swatinem/rust-cache@v2

      - name: Build and Test
        run: cargo test --workspace --release

      - name: Upload Gateway Binary
        uses: actions/upload-artifact@v4
        with:
          name: gateway-binary
          path: target/release/gateway
